### ISSUE TITLE
app is misreading geocode service response?

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent2.0#30]
searching for "33.720733,-84.376781" takes me to a bunch of different places depending on where the map is positioned. it also sometimes brings up crabapple #33. 

if you monitor the network devtools, it makes this request: `https://maps.googleapis.com/maps/api/geocode/json?key=[apikey]&address=33.720733,-84.376781`

and gets this response:

``` json
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "1241",
               "short_name" : "1241",
               "types" : [ "street_number" ]
            },
            ...
         ],
         "formatted_address" : "1241 Grant St SE, Atlanta, GA 30315, USA",
         "geometry" : {
            "location" : {
               "lat" : 33.720743,
               "lng" : -84.376997
            },
```

which is the right address.

**Comment by ThePlushEater** [comment]
Could you pull the most recent master branch? I found the second bug that you mentioned that brings up a tree instead of location, because I have a call back function to bring up a tree to the center when a popup is opened. I fixed this issue so the second issue should be solved by pulling the up-to-date master branch. And let me know again it happens again. (I haven't pushed as a new release, but it is stable version).

About the first issue, I suspect that my calculation to find the nearest place might be wrong. I will check again.

**Comment by durkie** [comment]
just pulled from master and rebuilt. still does not point to correct location when i search for 33.720733,-84.376781 (and still points to different locations depending on where the map is)
